CONFIG -= qt

TEMPLATE = lib
TARGET=YellowWeek02

CONFIG += c++1z
QMAKE_CXXFLAGS += -Werror

DEFINES += QT_DEPRECATED_WARNINGS
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    

HEADERS += \
    yl_w2_e01.h
